let weekIndex = localStorage.getItem('weekIndex')
if (weekIndex === null) localStorage.setItem('weekIndex', '0')
weekIndex = Number(localStorage.getItem('weekIndex'))

let timeOffset = localStorage.getItem('timeOffset')
if (timeOffset === null) localStorage.setItem('timeOffset', '0')
timeOffset = Number(localStorage.getItem('timeOffset'))

let dayOffset = localStorage.getItem('dayOffset')
if (dayOffset === null) localStorage.setItem('dayOffset', '-1')
dayOffset = Number(localStorage.getItem('dayOffset'))

let setDayOffsetLastDay = localStorage.getItem('setDayOffsetLastDay')
if (setDayOffsetLastDay === null) localStorage.setItem('setDayOffsetLastDay', '-1')
setDayOffsetLastDay = Number(localStorage.getItem('setDayOffsetLastDay'))


function getCurrentEditedDate() {
    let d = new Date();
    d.setSeconds(d.getSeconds() + Number.parseInt(timeOffset))
    return d;
}

function getCurrentEditedDay(date) {
    if (Number.parseInt(dayOffset) === -1)
        return date.getDay();
    if (Number.parseInt(setDayOffsetLastDay) === new Date().getDay()) {
        return dayOffset;
    }
    localStorage.setItem('dayOffset', '-1')
    localStorage.setItem('setDayOffsetLastDay', '-1')
    dayOffset = -1
    setDayOffsetLastDay = -1
    return date.getDay();
}

function isBreakTime(startTime, endTime, currentTime) {
    // 这俩东西我也不知道原作者怎么想的，实现逻辑一模一样
    return isClassCurrent(startTime, endTime, currentTime)
}

// Generated by ChatGPT4
function getCurrentDaySchedule() {
    const date = getCurrentEditedDate();
    const dayOfWeek = getCurrentEditedDay(date); // 0 = Sunday, 1 = Monday, ...
    const weekNumber = weekIndex; // 当前周数
    const dailyClass = scheduleConfig.daily_class[dayOfWeek];
    if (!dailyClass) return [];
    return dailyClass.classList.map(subject => {
        if (Array.isArray(subject)) {
            return subject[weekNumber]; // 处理每周不同的课程
        }
        return subject;
    });
}

function isClassCurrent(startTime, endTime, currentTime) {
    const [startH, startM] = startTime.split(':').map(Number);
    const [endH, endM] = endTime.split(':').map(Number);
    const [currentH, currentM] = currentTime.split(':').map(Number);

    const startMinutes = startH * 60 + startM;
    const endMinutes = endH * 60 + endM;
    const currentMinutes = currentH * 60 + currentM;

    return currentMinutes >= startMinutes && currentMinutes <= endMinutes;
}

function getCurrentTime() {
    const now = getCurrentEditedDate();
    return [
        now.getHours().toString().padStart(2, '0'),
        now.getMinutes().toString().padStart(2, '0'),
        now.getSeconds().toString().padStart(2, '0')
    ].join(':');
}

function setCurrentHighlightExternal(currentHighlight, index, type, fullName, endTime, currentTime, isEnd = false) {
        currentHighlight.index = index;
        currentHighlight.type = type;
        currentHighlight.fullName = fullName;
        currentHighlight.countdown = calculateCountdown(endTime, currentTime);
        currentHighlight.countdownText = formatCountdown(currentHighlight.countdown);
        if (isEnd) currentHighlight.isEnd = true;
    }

function findUpcomingExternal(index, timeRange, timeRanges, dayTimetable, scheduleArray, currentSchedule, currentTime, currentHighlight) {
        for (let i = index + 1; i < timeRanges.length; i++) {
            const nextTimeRange = timeRanges[i];
            const nextClassIndex = dayTimetable[nextTimeRange];
            if (typeof nextClassIndex === 'number') {
            setCurrentHighlightExternal(currentHighlight, scheduleArray.length, 'upcoming', dayTimetable[timeRange], timeRange.split('-')[1], currentTime);
                return true;
            }
        }
    setCurrentHighlightExternal(currentHighlight, currentSchedule.length - 1, 'upcoming', dayTimetable[timeRange], timeRange.split('-')[1], currentTime, true);
        return false;
    }

function getScheduleData() {
    const currentSchedule = getCurrentDaySchedule();
    const currentTime = getCurrentTime();
    const dayOfWeek = getCurrentEditedDay(getCurrentEditedDate());
    const timetable = scheduleConfig.daily_class[dayOfWeek].timetable;
    const dayTimetable = scheduleConfig.timetable[timetable];
    const divider = scheduleConfig.divider[timetable];
    let scheduleArray = [];
    let currentHighlight = { index: null, type: null, fullName: null, countdown: null, countdownText: null };

    const timeRanges = Object.keys(dayTimetable);

    for (const [index, timeRange] of timeRanges.entries()) {
        const [startTime, endTime] = timeRange.split('-');
        const classIndex = dayTimetable[timeRange];

        if (typeof classIndex === 'number') {
            const subjectShortName = currentSchedule[classIndex];
            const subjectFullName = scheduleConfig.subject_name[subjectShortName];
            scheduleArray.push(subjectShortName);

            if (isClassCurrent(startTime, endTime, currentTime)) {
                setCurrentHighlightExternal(currentHighlight, scheduleArray.length - 1, 'current', subjectFullName, endTime, currentTime);
            }
        } else if (currentHighlight.index === null && isBreakTime(startTime, endTime, currentTime)) {
            findUpcomingExternal(index, timeRange, timeRanges, dayTimetable, scheduleArray, currentSchedule, currentTime, currentHighlight);
        } else if (currentHighlight.index === null && !dayTimetable[timeRange]) {
            currentHighlight.fullName = currentSchedule[classIndex];
        }
    }

    return { scheduleArray, currentHighlight, timetable, divider };
}


function calculateCountdown(targetTime, currentTime) {
    const [targetH, targetM] = targetTime.split(':').map(Number);
    const [currentH, currentM, currentS = '00'] = currentTime.split(':').map(Number);

    const targetTotalSeconds = targetH * 3600 + (targetM + 1) * 60;
    const currentTotalSeconds = currentH * 3600 + currentM * 60 + currentS;

    return targetTotalSeconds - currentTotalSeconds;
}

function formatCountdown(countdownSeconds) {
    const minutes = Math.floor(countdownSeconds / 60);
    const seconds = countdownSeconds % 60;
    return `${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
}

