name: 给课表增添装饰
description: 点击此项使课表更好用
title: '[新功能?]: '
labels: [ "新功能？" ]
assignees: [ "daizihan233" ]

body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您愿意花一些时间来填写这个内容！
        ## 以下是一些注意事项，请务必阅读让我能够更容易处理

        ### ❗ | 确定没有相同提议的ISSUE已被提出。
        ### ❔ | 提议时，如果文字无法说明清楚，不妨使用画图的方法辅助说明
        ### ⚠ | 如果涉及敏感信息，请自行打码

        ## 如果您不知道如何有效、精准地表述，我建议您先阅读《提问的智慧》
        链接: [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
        ---
  - type: checkboxes
    id: terms
    attributes:
      label: |
        请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: "我已经仔细阅读上述教程和 [\"《提问的智慧》\"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。"
          required: true
        - label: "我确定这不是一个伪需求。"
          required: true
        - label: "我确定这是一个有意义的Issue，且目前没有解决方案。"
          required: true
        - label: "我确定在最近的 commit 提交所对应的版本中没有这个功能"
          required: true
  - type: checkboxes
    id: captcha
    attributes:
      label: |
        为了确保你是人类，请阅读并勾选以下内容，如有错选本仓库所有者可能会直接关闭此 Issue。
      options:
        - label: "我保证我已经认真阅读了以上说明，并已经勾选上面的选项"  # y
        - label: "我不确定我有认真阅读了以上说明，并没有勾选了上面的选项"  # x
        - label: "我确定我没有已经认真阅读了以上说明，并已经勾选上面的选项"  # x
        - label: "我不否认我确认了我已经认真阅读了以上说明，并否认我确定没有勾选上面的选项"  # y
        - label: "我确定我没有认真阅读了以上说明，并没有勾选上面的选项"  # x
        - label: "我不确定我没有认真阅读了以上说明，并勾选了上面的选项"  # y
        - label: "我承诺我以上所勾选的信息是不属实的"  # x
        - label: "我承诺我以上所勾选的信息不是错误的"  # y

  - type: markdown
    attributes:
      value: |
        ## 相关信息
        请根据实际使用环境修改以下信息。

  - type: input
    id: name
    attributes:
      label: 新功能名称
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 新功能描述
      description: 简述这个功能是干嘛的
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 新功能意义
      description: 简述这个功能的意义在哪
    validations:
      required: true

  - type: textarea
    id: how-to
    attributes:
      label: 实现方案（可选）
      description: 如果您有什么好的实现方案，那么可以写在这里

  - type: textarea
    id: extra-desc
    attributes:
      label: 补充说明（可选）
